public:
  bind:
    address: 'localhost'
    
  cors:
  allowedOrigin: ['http://git.elvns.com','https://git.elvns.com']
  
  redirectUrl: 'https://git.elvns.com'
  
  rateLimit: false

  handleInternalErrors: false
