public:
  metrics:
    prometheus:
      enabled: true

  ssl:
    isSecure: true

  cors:
    allowedOrigin: ['https://elvbadges.elvns.com', 'https://elvbadges.elvns.com']

  redirectUrl: 'https://elvbadges.elvns.com/'

  rasterUrl: 'https://raster.shields.io'

private:
  # These are not really private; they should be moved to `public`.
  shields_ips: ['192.99.59.72', '51.254.114.150']
